baseURL = 'https://christinesfn.pages.dev/'
relativeURLs = "true"
languageCode = 'en-us'
title = "Christine's Fields Note"
theme = 'nostyleplease'

[taxonomies]
  bookshelf = "bookshelf"
  people = "people"
  questions = "questions"
  tag = "tags"